import pytest
import sys
from pathlib import Path
from kaggle_prep.env_pin import (
    generate_pinned_requirements,
    generate_conda_environment,
    check_environment,
    format_env_check_summary,
)


def test_generate_pinned_requirements(tmp_path):
    req_file = generate_pinned_requirements(
        imports=["pandas", "numpy"],
        output_dir=str(tmp_path),
        filename="req.txt"
    )
    assert req_file.exists()

    content = req_file.read_text(encoding="utf-8")
    assert f"Generated by kaggle-prep on Python {sys.version.split()[0]}" in content
    assert "pandas==" in content
    assert "numpy==" in content


def test_generate_conda_environment(tmp_path):
    env_file = generate_conda_environment(
        env_name="test-env",
        imports=["pandas"],
        output_dir=str(tmp_path),
        filename="env.yml"
    )
    assert env_file.exists()

    content = env_file.read_text(encoding="utf-8")
    assert "name: test-env" in content
    assert "pandas==" in content


def test_check_environment_clean(tmp_path):
    req_file = generate_pinned_requirements(
        imports=["pandas", "numpy"],
        output_dir=str(tmp_path),
        filename="clean_req.txt"
    )
    res = check_environment(str(req_file))
    assert res["has_drift"] is False
    assert len(res["mismatched"]) == 0
    assert len(res["missing"]) == 0
    assert len(res["matched"]) >= 2


def test_check_environment_mismatch_detection(tmp_path):
    mismatch_file = tmp_path / "mismatch.txt"
    mismatch_file.write_text("pandas==0.0.1\nnonexistentpkg12345==9.9.9\n", encoding="utf-8")

    res = check_environment(str(mismatch_file))
    assert res["has_drift"] is True
    assert len(res["mismatched"]) == 1
    assert res["mismatched"][0]["package"] == "pandas"
    assert res["mismatched"][0]["pinned"] == "0.0.1"

    assert len(res["missing"]) == 1
    assert res["missing"][0]["package"] == "nonexistentpkg12345"

    summary = format_env_check_summary(res)
    assert "Version Mismatches Detected:" in summary
    assert "pandas" in summary
