"""
Environment pinning and verification module for kaggle-prep.
Generates pinned requirements.txt and environment.yml based on runtime environment introspection,
and validates environment reproducibility via --check-env.
"""

import sys
import importlib.metadata
from pathlib import Path
from typing import List, Dict, Tuple, Optional, Any


# Mapping from standard Python import names to PyPI package distribution names
IMPORT_TO_DISTRIBUTION = {
    "pd": "pandas",
    "pandas": "pandas",
    "np": "numpy",
    "numpy": "numpy",
    "plt": "matplotlib",
    "matplotlib": "matplotlib",
    "sns": "seaborn",
    "seaborn": "seaborn",
    "scipy": "scipy",
    "sklearn": "scikit-learn",
    "openpyxl": "openpyxl",
    "sqlalchemy": "sqlalchemy",
}


def get_installed_package_version(dist_name: str) -> Optional[str]:
    """Retrieve installed version of a package distribution via importlib.metadata."""
    try:
        return importlib.metadata.version(dist_name)
    except importlib.metadata.PackageNotFoundError:
        return None


def generate_pinned_requirements(
    imports: List[str] = None,
    output_dir: str = "notebooks",
    filename: str = "requirements.txt"
) -> Path:
    """
    Generate requirements.txt pinning installed package versions for given imported packages.
    Includes Python runtime version header comment.
    """
    if imports is None:
        imports = ["pandas", "numpy", "matplotlib", "seaborn", "scikit-learn", "scipy"]

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    req_file = output_path / filename

    dist_names = set()
    for imp in imports:
        dist = IMPORT_TO_DISTRIBUTION.get(imp, imp)
        dist_names.add(dist)

    lines = [
        f"# Generated by kaggle-prep on Python {sys.version.split()[0]}",
        "# Pinned dependencies for reproducible execution",
        ""
    ]

    for dist in sorted(dist_names):
        ver = get_installed_package_version(dist)
        if ver:
            lines.append(f"{dist}=={ver}")
        else:
            lines.append(f"# {dist} (not installed in current environment)")

    with open(req_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return req_file


def generate_conda_environment(
    env_name: str = "kaggle-prep-env",
    imports: List[str] = None,
    output_dir: str = "notebooks",
    filename: str = "environment.yml"
) -> Path:
    """Generate Conda environment.yml pinning installed package versions."""
    if imports is None:
        imports = ["pandas", "numpy", "matplotlib", "seaborn", "scikit-learn", "scipy"]

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    env_file = output_path / filename

    py_version = f"{sys.version_info.major}.{sys.version_info.minor}"
    dist_names = set()
    for imp in imports:
        dist = IMPORT_TO_DISTRIBUTION.get(imp, imp)
        dist_names.add(dist)

    pip_deps = []
    for dist in sorted(dist_names):
        ver = get_installed_package_version(dist)
        if ver:
            pip_deps.append(f"    - {dist}=={ver}")

    content = [
        f"name: {env_name}",
        "channels:",
        "  - defaults",
        "  - conda-forge",
        "dependencies:",
        f"  - python={py_version}",
        "  - pip",
        "  - pip:",
        *pip_deps,
        ""
    ]

    with open(env_file, "w", encoding="utf-8") as f:
        f.write("\n".join(content))

    return env_file


def check_environment(req_file_path: str) -> Dict[str, Any]:
    """
    Compare current runtime environment against pinned requirements file.
    Returns audit dict with matched, mismatched, and missing packages.
    """
    req_path = Path(req_file_path)
    if not req_path.exists():
        raise FileNotFoundError(f"Requirements file not found: {req_file_path}")

    matched = []
    mismatched = []
    missing = []

    with open(req_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            if "==" in line:
                pkg_name, pinned_ver = line.split("==", 1)
                pkg_name = pkg_name.strip()
                pinned_ver = pinned_ver.strip()
            else:
                pkg_name = line.strip()
                pinned_ver = None

            current_ver = get_installed_package_version(pkg_name)
            if current_ver is None:
                missing.append({"package": pkg_name, "pinned": pinned_ver})
            elif pinned_ver and current_ver != pinned_ver:
                mismatched.append({"package": pkg_name, "pinned": pinned_ver, "current": current_ver})
            else:
                matched.append({"package": pkg_name, "version": current_ver})

    has_drift = len(mismatched) > 0 or len(missing) > 0
    return {
        "has_drift": has_drift,
        "matched": matched,
        "mismatched": mismatched,
        "missing": missing,
    }


def format_env_check_summary(check_results: Dict[str, Any]) -> str:
    """Format check_environment results for CLI display."""
    lines = [
        "=" * 55,
        "  Environment Pinning & Reproducibility Check",
        "=" * 55,
    ]

    if not check_results["has_drift"]:
        lines.append(" Clean! Current environment matches pinned requirements perfectly.")
    else:
        if check_results["mismatched"]:
            lines.append("\n Version Mismatches Detected:")
            for item in check_results["mismatched"]:
                lines.append(f"   ! {item['package']}: pinned {item['pinned']} != current {item['current']}")

        if check_results["missing"]:
            lines.append("\n Missing Packages Detected:")
            for item in check_results["missing"]:
                lines.append(f"   x {item['package']}: pinned {item['pinned']} (not installed)")

    lines.append("=" * 55)
    return "\n".join(lines)
