"""
Pipeline exporter module for kaggle-prep.
Generates reusable, production-ready scikit-learn Pipeline Python module (`pipeline.py`)
and accompanying pytest verification suite (`test_pipeline.py`).
"""

import sys
from pathlib import Path
from typing import Optional, Dict, Any, List, Tuple
import pandas as pd
import numpy as np


def export_pipeline_code(
    df: pd.DataFrame,
    target_col: Optional[str] = None,
    task_type: Optional[str] = None,
    output_dir: str = "src"
) -> Tuple[Path, Path]:
    """
    Export scikit-learn Pipeline code module (`pipeline.py`) and pytest file (`test_pipeline.py`).

    Returns:
        Tuple of (path_to_pipeline_py, path_to_test_pipeline_py)
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    pipeline_py = output_path / "pipeline.py"
    test_py = output_path / "test_pipeline.py"

    if target_col and target_col in df.columns:
        X = df.drop(columns=[target_col])
    else:
        X = df

    num_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
    cat_cols = X.select_dtypes(include=["object", "category", "bool"]).columns.tolist()

    is_clf = (task_type and "classification" in task_type) or (not task_type and target_col and df[target_col].nunique() < 20)

    # 1. Build pipeline.py content
    pipeline_code = f'''"""
Production-ready Machine Learning Pipeline Module
Generated by kaggle-prep.
"""

from typing import Tuple, Any
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
{'from sklearn.ensemble import RandomForestClassifier' if is_clf else 'from sklearn.ensemble import RandomForestRegressor'}


NUMERIC_FEATURES = {num_cols}
CATEGORICAL_FEATURES = {cat_cols}


def build_pipeline() -> Pipeline:
    """Build and return an unfitted scikit-learn preprocessing and modeling Pipeline."""
    numeric_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])

    categorical_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', numeric_transformer, NUMERIC_FEATURES),
            ('cat', categorical_transformer, CATEGORICAL_FEATURES)
        ]
    )

    model = {'RandomForestClassifier(n_estimators=100, random_state=42)' if is_clf else 'RandomForestRegressor(n_estimators=100, random_state=42)'}

    pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('model', model)
    ])

    return pipeline


def train(X: pd.DataFrame, y: pd.Series) -> Pipeline:
    """Fit the pipeline on training features X and target y."""
    pipeline = build_pipeline()
    pipeline.fit(X, y)
    return pipeline


def predict(pipeline: Pipeline, X: pd.DataFrame) -> np.ndarray:
    """Generate predictions using the fitted pipeline."""
    return pipeline.predict(X)
'''

    with open(pipeline_py, "w", encoding="utf-8") as f:
        f.write(pipeline_code)

    # 2. Build test_pipeline.py content
    sample_data_code = f"""import pytest
import pandas as pd
import numpy as np
from pipeline import build_pipeline, train, predict, NUMERIC_FEATURES, CATEGORICAL_FEATURES


@pytest.fixture
def sample_dataset():
    # Create a sample dataset matching the schema
    n_rows = 20
    data = {{}}
    for col in NUMERIC_FEATURES:
        data[col] = np.random.randn(n_rows)
    for col in CATEGORICAL_FEATURES:
        data[col] = np.random.choice(['cat_A', 'cat_B'], size=n_rows)

    X = pd.DataFrame(data)
    y = np.random.choice([0, 1], size=n_rows) if {is_clf} else np.random.randn(n_rows)
    return X, y


def test_pipeline_fit_predict(sample_dataset):
    X, y = sample_dataset
    pipeline = train(X, y)
    preds = predict(pipeline, X)
    assert len(preds) == len(X)
    assert not np.isnan(preds).any()
"""

    with open(test_py, "w", encoding="utf-8") as f:
        f.write(sample_data_code)

    return pipeline_py, test_py
